name = BD Custom Layout
description = 3 column layout.
preview = preview.png
template = bd_custom-layout

; Regions
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content_before] = Before Content
regions[content]        = Content
regions[content_after]  = After Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/bd_custom/bd_custom.layout.css
